default_install_hook_types: [pre-commit]
default_stages: [commit, push]
default_language_version:
  python: python3.11
ci:
    autofix_commit_msg: |
        ci(pre-commit): Autofixing commit msg from pre-commit.com hooks
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: 'ci(autoupdate): Autoupdating commit msg'
    autoupdate_schedule: weekly
    skip: []
    submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: debug-statements
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: [ "--config=pyproject.toml" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)
      args: [ "--config=pyproject.toml" ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        args:
          - --config-file=backend/pyproject.toml
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=160", "--max-doc-length=140", "--ignore=E203,W503,F401,F403,F405,F541,F811"]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.2
    hooks:
      - id: pydocstyle
        args: [ "--ignore=E203,D100,D101,D102,D106,D103,D104,D105,D107,D203,D212,D213,D408,D413" ]
  - repo: local
    hooks:
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: venv/bin/alembic check
      types: ["python"]
      pass_filenames: false
